Bibliotecas importantes

In [26]:
import pandas as pd
import plotly.express as px

# Tratamento para "Dados_das_operadoras_TabNet.csv"

Entendimento inicial

In [27]:
# Leitura dos dados
path = "Dados_das_operadoras_TabNet.csv"
df_dados_das_operadoras_tabnet = pd.read_csv(path, sep=';', encoding='utf-8')
df_dados_das_operadoras_tabnet_novo = df_dados_das_operadoras_tabnet.copy()

In [28]:
print("Formato do dataset:", df_dados_das_operadoras_tabnet.shape)
print("\nColunas disponíveis:\n", df_dados_das_operadoras_tabnet.columns.tolist())
print("\nTipos de dados:\n", df_dados_das_operadoras_tabnet.dtypes)
print("\nValores ausentes:\n", df_dados_das_operadoras_tabnet.isna().sum())

Formato do dataset: (899, 29)

Colunas disponíveis:
 ['Operadora', 'Acre', 'Alagoas', 'Amap�', 'Amazonas', 'Bahia', 'Cear�', 'Distrito Federal', 'Esp�rito Santo', 'Goi�s', 'Maranh�o', 'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Par�', 'Para�ba', 'Paran�', 'Pernambuco', 'Piau�', 'Rio de Janeiro', 'Rio Grande do Norte', 'Rio Grande do Sul', 'Rond�nia', 'Roraima', 'Santa Catarina', 'S�o Paulo', 'Sergipe', 'Tocantins', 'Total']

Tipos de dados:
 Operadora              object
Acre                    int64
Alagoas                 int64
Amap�                   int64
Amazonas                int64
Bahia                   int64
Cear�                   int64
Distrito Federal        int64
Esp�rito Santo          int64
Goi�s                   int64
Maranh�o                int64
Mato Grosso             int64
Mato Grosso do Sul      int64
Minas Gerais            int64
Par�                    int64
Para�ba                 int64
Paran�                  int64
Pernambuco              int64
Piau�                   int64
Rio de Janeiro          int64
Rio Grande do Norte     int64
Rio Grande do Sul       int64
Rond�nia                int64
Roraima                 int64
Santa Catarina          int64
S�o Paulo               int64
Sergipe                 int64
Tocantins               int64
Total                   int64
dtype: object

Valores ausentes:
 Operadora              0
Acre                   0
Alagoas                0
Amap�                  0
Amazonas               0
Bahia                  0
Cear�                  0
Distrito Federal       0
Esp�rito Santo         0
Goi�s                  0
Maranh�o               0
Mato Grosso            0
Mato Grosso do Sul     0
Minas Gerais           0
Par�                   0
Para�ba                0
Paran�                 0
Pernambuco             0
Piau�                  0
Rio de Janeiro         0
Rio Grande do Norte    0
Rio Grande do Sul      0
Rond�nia               0
Roraima                0
Santa Catarina         0
S�o Paulo              0
Sergipe                0
Tocantins              0
Total                  0
dtype: int64

In [29]:
# Pequena amostra dos dados
df_dados_das_operadoras_tabnet.head()

,Operadora,Acre,Alagoas,Amap�,Amazonas,Bahia,Cear�,Distrito Federal,Esp�rito Santo,Goi�s,...,Rio de Janeiro,Rio Grande do Norte,Rio Grande do Sul,Rond�nia,Roraima,Santa Catarina,S�o Paulo,Sergipe,Tocantins,Total
0,000477-SUL AM�RICA SEGURADORA DE SA�DE S.A.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,000515-ALLIANZ SA�DE S/A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,000582-PORTO SEGURO - SEGURO SA�DE S/A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,000701-UNIMED SEGUROS SA�DE S/A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,000884-ITAUSEG SA�DE S.A.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

Tratamento

In [30]:
estados_cols = df_dados_das_operadoras_tabnet_novo.columns[1:-1]

df_dados_das_operadoras_tabnet_novo['estados'] = df_dados_das_operadoras_tabnet_novo.apply(
    lambda row: ', '.join([col for col in estados_cols if row[col] == 1]),
    axis=1
)

df_dados_das_operadoras_tabnet_novo = df_dados_das_operadoras_tabnet_novo.drop(columns=estados_cols)
df_dados_das_operadoras_tabnet_novo = df_dados_das_operadoras_tabnet_novo.drop(columns=['Total'])
df_dados_das_operadoras_tabnet_novo = df_dados_das_operadoras_tabnet_novo[df_dados_das_operadoras_tabnet_novo['Operadora'] != 'Total']
df_dados_das_operadoras_tabnet_novo

                                             Operadora         estados
0          000477-SUL AM�RICA SEGURADORA DE SA�DE S.A.       S�o Paulo
1                             000515-ALLIANZ SA�DE S/A       S�o Paulo
2               000582-PORTO SEGURO - SEGURO SA�DE S/A       S�o Paulo
3                      000701-UNIMED SEGUROS SA�DE S/A       S�o Paulo
4                            000884-ITAUSEG SA�DE S.A.       S�o Paulo
..                                                 ...             ...
893                   424048-VALE PLANOS DE SA�DE LTDA      Pernambuco
894                     424064-MB PLANOS DE SA�DE LTDA           Bahia
895   424129-HOSPITAL MATERNIDADE S�O VICENTE DE PAULO           Cear�
896                             424170-BLUZZ SA�DE S/A  Esp�rito Santo
897  424188-SERV  SOCIAL AUT�NOMO DE ASSIST � SA�DE...           Goi�s

[898 rows x 2 columns]

In [31]:
df_dados_das_operadoras_tabnet_novo.to_csv('../dados_tratados/Dados_das_operadoras_TabNet_tratado.csv', index=False)